CREATE DATABASE burgers_db;

USE burgers_db;

CREATE TABLE burgers (
id INT AUTO_INCREMENT NOT NULL,
PRIMARY KEY (id),
name VARCHAR(255) NOT NULL,
devoured BOOLEAN DEFAULT 0,
created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);